// speciesList.js

// Create an array of possible species names
const speciesList = [
  "Arcturian",
  "Andromedan",
  "Zephyrian",
  "Cepheid",
  "Ursian",
  "Draconian",
  "Rigelian",
  "Cygnian",
  "Antarean",
  "Eltarian",
  "Taurian",
  "Regulan",
  "Betelgeusian",
  "Orionian",
  "Altairian",
  "Eridanian",
  "Lyrian",
  "Pleiadian",
  "Aldebaran",
  "Procyonian",
  "Hyracian",
  "Rigelian",
  "Vindemiatrixian",
  "Canopican",
  "Delphinian",
  "Aquilian",
  "Fomalhautian",
  "Siriusian",
  "Luytenian",
  "Polluxian",
  "Wolfian",
  "Polarisian",
  "Denebian",
  "Vegaian",
  "Atrian",
  "Bellatrixian",
  "Capellian",
  "Deneb-Kaitosian",
  "Arcturian",
  "Proximian",
  "Altarian",
  "Mirfakian",
  "Denubian",
  "Gacruxian",
  "Alnilamian",
  "Atikarian",
  "Alhenaian",
  "Sadalmelikian",
  "Acruxian",
  "Menkabian",
  "Alnilamian",
  "Alhenaian",
  "Bellatrixian",
  "Betelgeusian",
  "Alnilamian",
  "Altairian",
  "Betelgeusian",
  "Rigelian",
  "Antarean",
  "Zephyrian",
  "Aldebaran",
  "Polarisian",
  "Arcturian",
  "Fomalhautian",
  "Alhenaian",
  "Deneb-Kaitosian",
  "Altairian",
  "Alnilamian",
  "Bellatrixian",
  "Vegaian",
  "Capell",
];

// Use a loop to generate 100 random species names and add them to the speciesList array
for (let i = 0; i < 100; i++) {
  speciesList.push("Species " + (i + 1));
}

// 20 starter abilities //
const specialAbilities = [
  { name: "Acid Spit", damage: 2 },
  { name: "Claws", damage: 3 },
  { name: "Healing Touch", health: 5 },
  { name: "Power Boost", fitness: 3 },
  { name: "Invisibility", health: -2 },
  { name: "Webbing", fitness: -1 },
  { name: "Venom", health: -3, damage: 3 },
  { name: "Sonic Scream", fitness: -2, damage: 4 },
  { name: "Regeneration", health: 4 },
  { name: "Phasing", fitness: 2 },
  { name: "Telekinesis", health: -1, damage: 3 },
  { name: "Telepathy", fitness: -2, damage: 4 },
  { name: "Heat Vision", health: -3, damage: 1 },
  { name: "Super Strength", fitness: 4, damage: 2 },
  { name: "Super Speed", health: 3 },
  { name: "Super Jump", fitness: 2 },
  { name: "Super Senses", health: 1 },
  { name: "Super Durability", fitness: 3 },
  { name: "Super Agility", health: 2 },
  { name: "Super Intelligence", fitness: 4 },
  { name: "Super Reflexes", health: 5, damage: 5 },
];

// Export the speciesList array
module.exports = speciesList;
